version: "2"
services:
        web:
                build: .
                command: ls && ./wait-for.sh
                volumes:
                        - .:/app/
                        - /app/node_modules
                ports:
                        - 3000:3000
                depends_on:
                        - mysql
                environment:
                  DATABASE_URL: mysql://hades:hades@mysql/hadesdb
                  DB_PASSWORD: hades
                  DB_USERNAME: hades
                  DB_PASSWORD: hades
                  DB_NAME: hadesdb
                  DB_HOSTNAME: mysql
        mysql:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: hadespwd
                        MYSQL_DATABASE: hadesdb
                        MYSQL_USER: hades
                        MYSQL_PASSWORD: hades
